version = 1

[[annotations]]
path = ".vscode/*.json"
SPDX-FileCopyrightText = "© 2026 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "© 2026 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "© 2026 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".clangd"
SPDX-FileCopyrightText = "© 2026 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/Doxyfile.in"
SPDX-FileCopyrightText = "© 2026 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "assets/GentiumBookPlus-Regular.ttf"
SPDX-FileCopyrightText = "© 2003-2022 SIL International (http://www.sil.org/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "assets/paddle.png"
SPDX-FileCopyrightText = "© 2003-2022 Jack Boakes (www.jackboakes.com)"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "assets/block_*.png"
SPDX-FileCopyrightText = "© 2003-2022 Jack Boakes (www.jackboakes.com)"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "assets/ball_default.png"
SPDX-FileCopyrightText = "© 2003-2022 Jack Boakes (www.jackboakes.com)"
SPDX-License-Identifier = "CC-BY-4.0"
